service: products
custom:
  awsAccountId: 271522064567  
  cognitoAuthorizer: arn:aws:cognito-idp:us-east-1:${self:custom.awsAccountId}:userpool/us-east-1_PmnLooJjR
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  timeout: 30     
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "dynamodb:Scan"
         - "dynamodb:Query"
         - "dynamodb:PutItem"
         - "dynamodb:DeleteItem"
         - "dynamodb:BatchWriteItem"
      Resource: [
        "arn:aws:dynamodb:us-east-1:*:table/Products"
      ]
functions:
  products:
    handler: functions/products.handler
    events:
      - http: get products  
      - http: 
          path: products
          method: post
          integration: lambda
          authorizer:
            arn: ${self:custom.cognitoAuthorizer}                
      - http:  
          path: products/{productId}
          method: put                    
          request: 
            parameters: 
              paths: 
                productId: true  
          integration: lambda       
          authorizer: 
            arn: ${self:custom.cognitoAuthorizer} 
      - http: 
          path: products/{productId}
          method: delete           
          request: 
            parameters: 
              paths: 
                productId: true   
          integration: lambda                
          authorizer: 
            arn: ${self:custom.cognitoAuthorizer}                                
      