service: products
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
         - "dynamodb:Scan"
         - "dynamodb:Query"
         - "dynamodb:PutItem"
         - "dynamodb:DeleteItem"
         - "dynamodb:BatchWriteItem"
      Resource: [
        "arn:aws:dynamodb:us-east-1:*:table/Products"
      ]
functions:
  products:
    handler: functions/products.handler
    events:
      - http: GET products    